// 業種・ユースケースのマスタ定義。クロス集計表の縦軸・横軸として使う。
// キーワード辞書は自動タグ付け（tagger.js）で使用する。

const INDUSTRIES = [
  { name: "製造業", keywords: ["工場", "製造", "組立", "manufactur", "factory", "assembly line", "automotive plant"] },
  { name: "自動車", keywords: ["自動車", "car factory", "automotive", "vehicle", "トラック", "truck", "自動運転", "self-driving", "robotaxi", "BMW", "Mercedes", "Hyundai", "Tesla"] },
  { name: "物流・倉庫", keywords: ["倉庫", "物流", "warehouse", "logistics", "fulfillment", "distribution center", "ピッキング", "picking"] },
  { name: "小売", keywords: ["小売", "店舗", "retail", "store", "supermarket", "スーパー", "品出し"] },
  { name: "農業", keywords: ["農業", "農場", "agriculture", "farm", "harvest", "収穫", "栽培", "tractor", "トラクター"] },
  { name: "建設", keywords: ["建設", "construction", "施工", "重機", "excavator", "工事現場", "job site"] },
  { name: "エネルギー", keywords: ["エネルギー", "energy", "送電", "発電", "power grid", "プラント", "plant inspection", "石油", "oil", "gas"] },
  { name: "医療・介護", keywords: ["医療", "病院", "介護", "healthcare", "hospital", "medical", "care facility", "elderly", "手術", "surgical", "nursing"] },
  { name: "食品", keywords: ["食品", "food", "厨房", "kitchen", "調理", "cooking", "盛り付け", "食品工場", "food processing"] },
  { name: "公共・インフラ", keywords: ["空港", "airport", "駅", "公共", "public infrastructure", "インフラ", "municipal", "自治体"] },
  { name: "接客・サービス", keywords: ["レストラン", "restaurant", "ホテル", "hotel", "接客", "配膳", "案内", "concierge", "hospitality", "サービス業"] },
  { name: "鉱業", keywords: ["鉱山", "鉱業", "mining", "mine", "copper mine", "gold mine", "haul truck", "採掘"] },
  { name: "港湾・海運", keywords: ["港湾", "海運", "port", "container terminal", "ガントリークレーン", "gantry crane"] },
  { name: "教育", keywords: ["学校", "教育", "school", "campus", "university", "学区", "キャンパス"] },
  { name: "宇宙", keywords: ["宇宙", "衛星", "satellite", "軌道", "geosynchronous"] }
];

const USE_CASES = [
  { name: "ピッキング・搬送", keywords: ["ピッキング", "picking", "搬送", "conveying", "material handling", "sorting", "仕分け"] },
  { name: "組立", keywords: ["組立", "assembly", "assemble"] },
  { name: "検品・品質管理", keywords: ["検品", "品質管理", "quality inspection", "quality control", "defect detection", "検査"] },
  { name: "自律走行・配送", keywords: ["自律走行", "自動運転", "配送", "autonomous driving", "self-driving", "delivery robot", "robotaxi", "last-mile"] },
  { name: "収穫・栽培管理", keywords: ["収穫", "harvest", "栽培", "cultivation", "crop monitoring", "農作業"] },
  { name: "危険作業代替", keywords: ["危険作業", "hazardous", "dangerous task", "有害", "災害対応", "disaster response"] },
  { name: "点検・保守", keywords: ["点検", "保守", "inspection", "maintenance", "メンテナンス", "monitoring equipment"] },
  { name: "清掃", keywords: ["清掃", "cleaning", "掃除"] },
  { name: "接客・案内", keywords: ["接客", "案内", "concierge", "guide robot", "customer service", "receptionist"] },
  { name: "調理・盛付", keywords: ["調理", "盛り付け", "盛付", "cooking", "food preparation", "plating"] },
  { name: "介護支援", keywords: ["介護支援", "介護", "elderly care", "nursing support", "リハビリ", "rehabilitation"] },
  { name: "在庫管理", keywords: ["在庫管理", "inventory management", "棚卸", "stock management"] },
  { name: "遠隔操作・監視", keywords: ["遠隔操作", "遠隔監視", "teleoperation", "remote monitoring", "telepresence"] },
  { name: "教育支援", keywords: ["教育支援", "教師アシスタント", "teaching assistant", "tutoring", "個別指導"] },
  { name: "手術支援", keywords: ["手術支援", "surgical", "surgery", "da Vinci", "ダ・ヴィンチ", "マイクロサージェリー"] },
  { name: "研究・実験", keywords: ["研究・実験", "実験室", "自律型ラボ", "laboratory", "research lab"] }
];

// ロボットベンダー（ロボット本体・自律走行システムの開発元）。
// 導入企業（company）とは別軸。1事例に複数ベンダーが紐づく場合もある。
const VENDORS = [
  { name: "Agility Robotics", keywords: ["Agility Robotics", "Digit"] },
  { name: "Figure AI", keywords: ["Figure AI", "Figure 03", "Figure 02"] },
  { name: "Hexagon Robotics", keywords: ["Hexagon Robotics", "AEON"] },
  { name: "Galbot", keywords: ["Galbot"] },
  { name: "UBTech", keywords: ["UBTech", "UBTECH", "Walker S2", "Walker E", "UWORLD"] },
  { name: "Boston Dynamics", keywords: ["Boston Dynamics", "Atlas"] },
  { name: "Humanoid", keywords: ["Alpha HMND", "Humanoid"] },
  { name: "Apptronik", keywords: ["Apptronik", "Apollo"] },
  { name: "Sanctuary AI", keywords: ["Sanctuary AI", "Phoenix"] },
  { name: "Accenture", keywords: ["Accenture", "Robot Brain"] },
  { name: "Amazon Robotics", keywords: ["Proteus", "Amazon Robotics"] },
  { name: "Reflex Robotics", keywords: ["Reflex Robotics"] },
  { name: "Rainbow Robotics", keywords: ["レインボーロボティクス", "Rainbow Robotics", "RB-Y1"] },
  { name: "AgiBot（智元）", keywords: ["智元", "AgiBot"] },
  { name: "Unitree", keywords: ["Unitree", "宇樹科技", "Go2"] },
  { name: "Kodiak AI", keywords: ["Kodiak"] },
  { name: "Waymo", keywords: ["Waymo"] },
  { name: "Pony.ai", keywords: ["Pony.ai"] },
  { name: "Zoox", keywords: ["Zoox"] },
  { name: "Xiaomi", keywords: ["Xiaomi"] },
  { name: "John Deere", keywords: ["John Deere"] },
  { name: "Kubota", keywords: ["Kubota"] },
  { name: "Agtonomy", keywords: ["Agtonomy"] },
  { name: "Built Robotics", keywords: ["Built Robotics"] },
  { name: "Gravis Robotics", keywords: ["Gravis Robotics"] },
  { name: "HD Hyundai", keywords: ["HD Hyundai"] },
  { name: "Komatsu", keywords: ["Komatsu"] },
  { name: "Quali Drone", keywords: ["Quali Drone"] },
  { name: "トヨタ", keywords: ["トヨタ", "Toyota", "Potaro"] },
  { name: "パナソニック", keywords: ["パナソニック", "Panasonic", "HOSPI"] },
  { name: "Intuitive Surgical", keywords: ["ダ・ヴィンチ", "da Vinci", "Intuitive"] },
  { name: "Enchanted Tools", keywords: ["Enchanted Tools", "Miroki"] },
  { name: "Preferred Robotics", keywords: ["Preferred Robotics"] },
  { name: "ソフトバンクロボティクス", keywords: ["ソフトバンクロボティクス", "SoftBank Robotics", "Pepper", "FLAMA"] },
  { name: "Pudu Robotics", keywords: ["Pudu Robotics", "BellaBot", "KettyBot", "CC1 Pro"] },
  { name: "IntBot", keywords: ["IntBot"] },
  { name: "Dexterity", keywords: ["Dexterity", "Mech", "Foresight"] },
  { name: "Kawasaki Robotics", keywords: ["Kawasaki Robotics", "RL030N"] },
  { name: "Doosan Robotics", keywords: ["Doosan Robotics"] },
  { name: "ABB Robotics", keywords: ["ABB Robotics", "HyperReality"] },
  { name: "Universal Robots", keywords: ["Universal Robots"] },
  { name: "Mobile Industrial Robots（MiR）", keywords: ["Mobile Industrial Robots", "MiR"] },
  { name: "Techman Robot", keywords: ["Techman Robot"] },
  { name: "Konecranes", keywords: ["Konecranes"] },
  { name: "IRID", keywords: ["IRID", "国際廃炉研究開発機構"] },
  { name: "Caterpillar", keywords: ["Caterpillar"] },
  { name: "SVT Robotics", keywords: ["SVT Robotics", "SOFTBOT"] },
  { name: "Realbotix", keywords: ["Realbotix", "Optio"] },
  { name: "ForwardX Robotics", keywords: ["ForwardX Robotics", "ForwardX"] },
  { name: "Geek+", keywords: ["Geek+", "ギークプラス"] },
  { name: "Aramine", keywords: ["Aramine"] },
  { name: "Epiroc", keywords: ["Epiroc", "AutoNav"] },
  { name: "Robust.AI", keywords: ["Robust.AI", "Carter"] },
  { name: "Medical Microinstruments", keywords: ["Medical Microinstruments", "Symani"] },
  { name: "Cainiao", keywords: ["Cainiao", "ZeeBot"] },
  { name: "GMEX Robotics", keywords: ["GMEX Robotics", "Bon Vivant"] },
  { name: "Serve Robotics", keywords: ["Serve Robotics", "Diligent Robotics", "Moxi"] },
  { name: "DailyRobotics", keywords: ["DailyRobotics"] },
  { name: "Taurob", keywords: ["Taurob"] },
  { name: "FieldAI", keywords: ["FieldAI"] },
  { name: "REVOBOTS", keywords: ["REVOBOTS", "TASKBOT"] },
  { name: "SpaceLogistics", keywords: ["SpaceLogistics", "Mission Robotic Vehicle", "DARPA"] },
  { name: "QSS AI & Robotics", keywords: ["QSS AI", "QSS Robotics"] },
  { name: "VinMotion", keywords: ["VinMotion"] },
  { name: "Mariana Minerals", keywords: ["Mariana Minerals", "MarianaOS"] },
  { name: "Skild AI", keywords: ["Skild AI", "Skild Brain"] },
  { name: "Oversonic Robotics", keywords: ["Oversonic Robotics", "RoBee"] },
  { name: "3Srobotics", keywords: ["3Srobotics", "昇視唯盛"] },
  { name: "Ultra", keywords: ["Ultra Robotics", "OP1", "Ultraroboticsco"] },
  { name: "Geely", keywords: ["Geely", "吉利"] },
  { name: "Lightwheel", keywords: ["Lightwheel", "Real2Sim2Real"] },
  { name: "Medra", keywords: ["Medra"] },
  { name: "Mimic Robotics", keywords: ["Mimic Robotics", "mimic-video"] },
  { name: "DEEP Robotics", keywords: ["DEEP Robotics"] },
  { name: "Robotic Biology Institute", keywords: ["Robotic Biology Institute", "まほろ"] },
  { name: "Wandercraft", keywords: ["Wandercraft", "Calvin"] },
  { name: "Lumos Robotics", keywords: ["Lumos Robotics"] },
  { name: "Persona AI", keywords: ["Persona AI"] },
];

// 事例が実際に導入・運用されている国。会社の国籍ではなく、記事内で確認できた導入先の国。
// vendorHints同様、本文全体からの自動検出はせずcountryHintsとのみ照合する（company表記との衝突を避けるため）。
const COUNTRIES = [
  { name: "日本", keywords: ["日本"] },
  { name: "アメリカ", keywords: ["アメリカ"] },
  { name: "中国", keywords: ["中国"] },
  { name: "韓国", keywords: ["韓国"] },
  { name: "ドイツ", keywords: ["ドイツ"] },
  { name: "イギリス", keywords: ["イギリス"] },
  { name: "カナダ", keywords: ["カナダ"] },
  { name: "スイス", keywords: ["スイス"] },
  { name: "デンマーク", keywords: ["デンマーク"] },
  { name: "オランダ", keywords: ["オランダ"] },
  { name: "ハンガリー", keywords: ["ハンガリー"] },
  { name: "ポルトガル", keywords: ["ポルトガル"] },
  { name: "台湾", keywords: ["台湾"] },
  { name: "マルタ", keywords: ["マルタ"] },
  { name: "アルゼンチン", keywords: ["アルゼンチン"] },
  { name: "チリ", keywords: ["チリ"] },
  { name: "メキシコ", keywords: ["メキシコ"] },
  { name: "オーストラリア", keywords: ["オーストラリア"] },
  { name: "UAE", keywords: ["UAE"] },
  { name: "サウジアラビア", keywords: ["サウジアラビア"] },
  { name: "ベトナム", keywords: ["ベトナム"] },
  { name: "エジプト", keywords: ["エジプト"] },
  { name: "シンガポール", keywords: ["シンガポール"] },
  { name: "フランス", keywords: ["フランス"] },
];

// ロボットタイプの分類。実装・研究中のロボットの物理形態による分類。
const ROBOT_TYPES = [
  { name: "ヒューマノイド", keywords: ["humanoid", "ヒューマノイド", "human-like", "人型", "biped", "phoenix", "apollo", "digit", "g1", "walker s", "motion_1", "mech"] },
  { name: "ロボットアーム", keywords: ["robot arm", "ロボットアーム", "manipulator", "collaborative arm", "cobot arm", "arm robot", "双腕", "ur10", "yamaha", "universal robot"] },
  { name: "四足歩行ロボット", keywords: ["quadruped", "四足", "4足", "quadlegged", "go2", "spot", "atlas", "x30"] },
  { name: "AMR/AGV", keywords: ["amr", "agv", "autonomous mobile robot", "autonomous guided vehicle", "自律走行ロボット", "mobile robot", "mir", "eve", "proteus", "autonomous vehicle"] },
  { name: "自動運転車", keywords: ["autonomous truck", "robotaxi", "ロボタクシー", "self-driving", "automated haul truck", "autonomous haul", "zodiac", "waymo", "pony.ai", "zoox", "kodiak"] },
  { name: "ドローン", keywords: ["drone", "ドローン", "uav", "quadcopter", "aerial robot", "unmanned aerial"] },
];

module.exports = { INDUSTRIES, USE_CASES, VENDORS, COUNTRIES, ROBOT_TYPES };
